// Auto-generated by scripts/generate-cms-client.mjs. Do not edit manually.

const DEFAULT_BASE_URL = process.env.NEXT_PUBLIC_CMS_API_URL || process.env.CMS_API_URL || 'http://localhost:4000';

export function createCmsClient(options = {}) {
  const baseUrl = options.baseUrl || DEFAULT_BASE_URL;
  const getAccessToken = options.getAccessToken || (() => options.token || (typeof window === 'undefined' ? process.env.CMS_API_TOKEN : undefined) || process.env.NEXT_PUBLIC_CMS_API_TOKEN);
  const defaultHeaders = options.defaultHeaders || {};

  async function request(path, { method = 'GET', query, init } = {}) {
    const url = new URL(path, baseUrl.endsWith('/') ? baseUrl : baseUrl + '/');
    if (query) {
      Object.entries(query)
        .filter(([, value]) => value !== undefined && value !== null)
        .forEach(([key, value]) => {
          url.searchParams.append(key, String(value));
        });
    }
    const headers = {
      ...defaultHeaders,
      ...(init?.headers ? init.headers : {}),
    };
    const token = getAccessToken ? getAccessToken() : undefined;
    if (token) {
      headers.Authorization = `Bearer ${token}`;
    }
    const response = await fetch(url.toString(), {
      method,
      ...init,
      headers,
    });
    if (!response.ok) {
      const message = await safeReadError(response);
      throw new Error(message);
    }
    if (response.status === 204) {
      return undefined;
    }
    return response.json();
  }

  return {
    async listProducts(query = {}, requestInit) {
      return request("/products", { method: 'GET', query: query, init: requestInit });
    },

    async getProduct(id, requestInit) {
      return request(`/products/${id}`, { method: 'GET', query: undefined, init: requestInit });
    },

    async listCategories(requestInit) {
      return request("/categories", { method: 'GET', query: undefined, init: requestInit });
    },

    async listPages(requestInit) {
      return request("/pages", { method: 'GET', query: undefined, init: requestInit });
    },

    async getPage(id, requestInit) {
      return request(`/pages/${id}`, { method: 'GET', query: undefined, init: requestInit });
    },

    async listBlocks(query = {}, requestInit) {
      return request("/blocks", { method: 'GET', query: query, init: requestInit });
    },

    async listMenus(requestInit) {
      return request("/menus", { method: 'GET', query: undefined, init: requestInit });
    },

    async getMenu(id, requestInit) {
      return request(`/menus/${id}`, { method: 'GET', query: undefined, init: requestInit });
    }
  };
}

async function safeReadError(response) {
  try {
    const data = await response.json();
    return data.message || response.statusText;
  } catch (error) {
    return response.statusText;
  }
}

export const defaultCmsClient = createCmsClient();
